name: deno-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: actions/checkout@v3
        run: corepack enable
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
        env:
          NITRO_PRESET: deno
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: important-starling-87
          entrypoint: server/index.ts
          root: .output
