name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - uses: pnpm/action-setup@v2 
        with: 
          version: 8
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Build step
        run: pnpm install && pnpm build # 📝 Update the build command(s)
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}
        

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "important-starling-87"
          entrypoint: "server/index.ts" # 📝 Update the entrypoint
          root: ".output"
